### ISSUE TITLE
fido2-hmac-secret binary references build path

### ISSUE THREAD

**Issue by Maryse47** [mjec/fido2-hmac-secret#13]
**Describe the bug**
Building with `makepkg` from Arch Linux (https://github.com/mjec/fido2-hmac-secret/pull/10) produces following warning:
`WARNING: Package contains reference to $srcdir`

Running `strings` on `fido2-hmac-secret` shows:
```
$ strings dist/bin/fido2-hmac-secret | grep -F /build/fido2-hmac-secret-git/src/fido2-hmac-secret/`
build/fido2-hmac-secret-git/src/fido2-hmac-secret/src/serialization/v1.c
/build/fido2-hmac-secret-git/src/fido2-hmac-secret/src/main.c
/build/fido2-hmac-secret-git/src/fido2-hmac-secret/src/authenticator.c
```
Is referencing build paths in produced binary intentional and needed?

**To Reproduce**
1. Run `make release`
2. Run ` strings dist/bin/fido2-hmac-secret | grep -F /build/path`

**Expected behavior**
??

**Environment:**
 - Operating system: Arch Linux
 - Version: https://github.com/mjec/fido2-hmac-secret/commit/e53bcd45f7da5ba8104e6429010b8216b6c41e36

**Comment by mjec** [comment]
I was very confused about this for a moment, but I've figured out what's happening here. There are a few references to `__FILE__` in strings relating to "should never happen" conditions: https://github.com/mjec/fido2-hmac-secret/search?utf8=%E2%9C%93&q=__FILE__&type=

I am comfortable leaving these in, though the warning is a little annoying. We could replace `__FILE__` with `__func__` I guess?

**Comment by Maryse47** [comment]
If possible I would be in favor of getting rid of those paths. Main reason for this is that it breaks reproducibility (also it's a small privacy leak).

**Comment by mjec** [comment]
Makes sense, I'll replace with `__func__`
