### ISSUE TITLE
Don't unconditionally require authenticator to exist in initcpio-run.m4

### ISSUE THREAD

**Issue by mjec** [mjec/fido2-hmac-secret#21]
**Is your feature request related to a problem? Please describe.**
It's frustrating to have to insert the FIDO2 authenticator before startup.

**Describe the solution you'd like**
An optional parameter passed to initcpio script results in a pause and prompt to insert authenticator if none is detected.

**Comment by Maryse47** [comment]
Can't it try to detect authenticator in a loop with a timeout (30s - 1m)? This way you won't need special option.
