### ISSUE TITLE
Broken link to AUR package

### ISSUE THREAD

**Issue by Maryse47** [mjec/fido2-hmac-secret#22]
**Describe the bug**
After project [rename](https://github.com/mjec/khefin/commit/1e9fe82d1e2b26ab8bb723ede07f515953da14fb) (what was the reason for it?), the link to AUR package is broken ([points to non-existing new package name](https://aur.archlinux.org/packages/khefin/)).

**Comment by mjec** [comment]
Great pickup, fixed!

The reasoning behind the rename is that the old name was both long and slightly misleading; this application doesn't provide the hmac-secret extension, it merely uses it. The new name has the virtues of being short and unique, though it is definitely less descriptive.
