### ISSUE TITLE
Add CanoKey to supported authenticators list

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [mjec/fido2-hmac-secret#32]
```
$ khefin enumerate
        /dev/hidraw1    Canokeys Canokey        244eb29e-e090-4e49-81fe-*
```
I tested with my Canokey.
```
$ lsusb -d 20a0:42d4
Bus 001 Device 002: ID 20a0:42d4 Clay Logic Canokey
```

For more info, please refer to the [doc](https://docs.canokeys.org/development/protocols/) stating it has hmac-secret and refer to the [code](https://github.com/canokeys/canokey-core)

**Comment by mjec** [comment]
[Added](https://github.com/mjec/khefin/wiki/Supported-authenticators), thanks!
