### ISSUE TITLE
Update wiki: appname incorrect

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [mjec/fido2-hmac-secret#33]
- In https://github.com/mjec/khefin/wiki/Arch-Linux-LUKS-configuration, the app name is `fido2-hmac-secret`. However, with recent releases the app name is `khefin`. So the name should be changed there. Also, the initcpio hook is now `khefin`
- `make release initcpio` should be `make release mkinitcpio`
- `/tmp/0-primary-authenticator.keyslot-1` should be `/tmp/0-primary-authenticator`, by its context
- You shall state that `keyfiles_source_dir=/boot/keyfiles` is the default value and user can ignore that. For other values, configs should be provided for making correct environment for auto-run `mkinitcpio -P` (such as being invoked by `pacman -Syu`)

**Comment by mjec** [comment]
Thank you, I think these are all fixed now!
