### ISSUE TITLE
systemd compatibility?

### ISSUE THREAD

**Issue by Diaoul** [mjec/fido2-hmac-secret#39]
The docs don't mention systemd or sd-encrypt. Is khefin hook compatible with this?

**Comment by mjec** [comment]
Hi @Diaoul, I'm afraid I'm not sufficiently familiar with sd-encrypt to be able to give you a definitive answer.

However, khefin's initcpio script works by setting the `cryptkey` kernel parameter, so if that's read by sd-encrypt it should work. If you're experimenting with this, I'd love to hear the outcome; and remember to make a backup of your luks header before you start!

**Comment by Diaoul** [comment]
I decided to try out [`systemd-cryptenroll` and systemd's native FIDO2 implementation](http://0pointer.net/blog/unlocking-luks2-volumes-with-tpm2-fido2-pkcs11-security-hardware-on-systemd-248.html) and try it out to see how it works. It's not exactly 2FA but with FIDO2 PIN prompting this is really close.
Got myself locked out in the process for a brief moment, where's the fun otherwise..
I might come back to trying khefin with systemd later as I had my share of adventures for now and I want to try systemd's version a bit more :smile:

**Comment by mjec** [comment]
Thanks for reporting back! I'm going to close this issue out for now, but feel free to reopen it in future if you come back to `khefin`.
