### ISSUE TITLE
PGP Keys - Keyserver receive failed: No data

### ISSUE THREAD

**Issue by emollusion** [mjec/fido2-hmac-secret#40]
While installing from AUR, the PGP key can not be imported which is a requirement for installation.

**To Reproduce**
1. yay -S khefin

**Expected behavior**
installation and download of pgp key

**Environment:**
 - Operating system: Linux 5.10.79-1-MANJARO
 - Version: khefin-0.6.1-2

**Additional context**
```
$ yay -S khefin
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  khefin-0.6.1-2

  1 khefin                                   (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/****/.cache/yay/khefin
:: (1/1) Downloaded PKGBUILD: khefin
  1 khefin                                   (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: khefin

:: PGP keys need importing:
 -> 6927F7D45F567621E14121DDFD1D670D31F82A81, required by: khefin
==> Import? [Y/n] 
:: Importing keys with gpg...
gpg: keyserver receive failed: No data
 -> problem importing keys
```

**Comment by mjec** [comment]
Hey @emollusion, thanks for the report.

This key is available [on Keybase](https://keybase.io/mjec/pgp_keys.asc?fingerprint=6927f7d45f567621e14121ddfd1d670d31f82a81) (linked in the PKGBUILD) and I've just submitted it to the [MIT keyserver](http://pgp.mit.edu).

If there's another keyserver that your installation is using, please feel free to submit the key to that keyserver as well. This will help out others, and is normally as simple as pasting the public key into a web form.
