### ISSUE TITLE
Not compatible with libcbor latest update

### ISSUE THREAD

**Issue by flapedriza** [mjec/fido2-hmac-secret#41]
**Describe the bug**
Khefin seems to not be compatible with the latest libcbor version (0.9.0)

**To Reproduce**
1. Update libcbor to 0.9.0
2. Use any khefin command (including simple ones like `khefin version`) (this includes when khefin loads on boot)
3. See error:
    ```
    khefin enumerate   
    khefin: error while loading shared libraries: libcbor.so.0.8: cannot open shared object file: No such file or directory
    ```

**Expected behavior**
No errors.

**Environment:**
 - Operating system: Arch linux
 - Version: 0.6.1
 - Authenticator make and model: Solokeys Solo Tap
 - Installed through AUR

**Comment by ZenithalHourlyRate** [comment]
```
$ pacman -Ql libcbor | grep so
libcbor /usr/lib/libcbor.so
libcbor /usr/lib/libcbor.so.0.9
libcbor /usr/lib/libcbor.so.0.9.0
```
You may just recompile your khefin AUR package?

**Comment by flapedriza** [comment]
> ```
> $ pacman -Ql libcbor | grep so
> libcbor /usr/lib/libcbor.so
> libcbor /usr/lib/libcbor.so.0.9
> libcbor /usr/lib/libcbor.so.0.9.0
> ```
> 
> You may just recompile your khefin AUR package?

I tried to do it but I still get the same error:
```
==> ERROR: binary dependency `libcbor.so.0.8' not found for `khefin'
  -> Running build hook: [encrypt]
==> WARNING: Possibly missing firmware for module: qat_4xxx
  -> Running build hook: [lvm2]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
Decompress:  1/766 files. Current: ...ph-dr-of.ko.zst : 0 B...    ==> Generating module dependencies
==> Creating zstd-compressed initcpio image: /boot/initramfs-linux-fallback.img
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
==> WARNING: errors were encountered during the build. The image may not be complete.
error: command failed to execute correctly
```

I downgraded libcbor to 0.8.0 and libfido2 to 1.8.0 (1.9 had libcbor 0.9 as dependency) and now it seems to work correctly.

**Comment by ZenithalHourlyRate** [comment]
By recompiling I meant `cleanBuild` when you install khefin via your AUR helper
```
$ ldd /usr/bin/khefin
        linux-vdso.so.1 (0x00007fffd99f2000)
        libfido2.so.1 => /usr/lib/libfido2.so.1 (0x00007f2245a10000)
        libcbor.so.0.9 => /usr/lib/libcbor.so.0.9 (0x00007f22459fe000)
        libsodium.so.23 => /usr/lib/libsodium.so.23 (0x00007f22459a4000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f22457d8000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f22454f7000)
        libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f22454ca000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f22454ae000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f2245a8c000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f224548d000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f2245486000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f224547b000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f2245460000)
```

Example:
```
$ yay -S khefin
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
```

**Comment by flapedriza** [comment]
> By recompiling I meant `cleanBuild` when you install khefin via your AUR helper
> 
> ```
> $ ldd /usr/bin/khefin
>         linux-vdso.so.1 (0x00007fffd99f2000)
>         libfido2.so.1 => /usr/lib/libfido2.so.1 (0x00007f2245a10000)
>         libcbor.so.0.9 => /usr/lib/libcbor.so.0.9 (0x00007f22459fe000)
>         libsodium.so.23 => /usr/lib/libsodium.so.23 (0x00007f22459a4000)
>         libc.so.6 => /usr/lib/libc.so.6 (0x00007f22457d8000)
>         libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f22454f7000)
>         libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f22454ca000)
>         libz.so.1 => /usr/lib/libz.so.1 (0x00007f22454ae000)
>         /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f2245a8c000)
>         libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f224548d000)
>         libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f2245486000)
>         librt.so.1 => /usr/lib/librt.so.1 (0x00007f224547b000)
>         libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f2245460000)
> ```
> 
> Example:
> 
> ```
> $ yay -S khefin
> ==> Packages to cleanBuild?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> A
> ```

Hi,
I was using pikaur and it doesn't ask you if you want a clean build if it has the build files in cache. I didn't realize that and I mistook the mkinitcpio log for the build log.
I deleted the cache of the package and built it again. Now it seems to work.

Many thanks for your help! And sorry for the possible noise I introduced.
