### ISSUE TITLE
Permit other KDF hardness options

### ISSUE THREAD

**Issue by mjec** [mjec/fido2-hmac-secret#5]
**Is your feature request related to a problem? Please describe.**
Currently `enrol` (and specifically `build_deserialized_cleartext_from_authenticator_parameters_and_passphrase()`) always uses the following parameters to `crypto_pwhash()`:

```
crypto_pwhash_OPSLIMIT_MODERATE
crypto_pwhash_MEMLIMIT_MODERATE
crypto_pwhash_ALG_ARGON2I13
```

This uses 256MB of memory and may not be suitable for some devices.

**Describe the solution you'd like**

Add command line parameters permitting three values: lowmem, default, himem.

Maybe low-security, default, high-security, that also captures opslimit?

Maybe split out opslimit and have that as an option too?

**Additional context**
Need to ensure `MEMLOCK_LIMIT_BYTES` is enough to handle himem/high-security.

**Comment by Maryse47** [comment]
I think 256MB is ok for security and high-security option isn't needed. lowmem could be the only concern here. Maybe there could be heuristics which detects available memory?

**Comment by mjec** [comment]
> I think 256MB is ok for security and high-security option isn't needed. lowmem could be the only concern here.

I was mostly thinking about exposing the [libsodium options](https://libsodium.gitbook.io/doc/password_hashing/default_phf), which require 64mb/256mb/1024mb respectively. I think in general, all of these are fine (the risk profile here is very different to a web application).

Moderate is a good default, but I think better to permit use on a memory-constrained device by specifying a `crypto_pwhash_MEMLIMIT_INTERACTIVE`-equivalent than provide a hard limit that precludes use of a system to improve security.

> Maybe there could be heuristics which detects available memory?

I think I'd prefer to be explicit and simple, on the principle that cryptogrpahic agility tends to be more bad than good. Specifically, while we can specify values directly, I'm a little hesitant to go outside anything that libsodium provides as a constant.

**Comment by Maryse47** [comment]
> I think I'd prefer to be explicit and simple, on the principle that cryptogrpahic agility tends to be more bad than good. Specifically, while we can specify values directly, I'm a little hesitant to go outside anything that libsodium provides as a constant.

I meant heuristics which will choose one of three options automatically without user input. For example you could detect amount of ram and use the highest one of 64mb/256mb/1024mb which is lower than half of ram.

**Comment by mjec** [comment]
> I meant heuristics which will choose one of three options automatically without user input.

Ahh yeah I can get behind that!

I'll code it up.
