### ISSUE TITLE
make install doesn't work for bash-completions and fido2-hmac-secret-add-luks-key manpage

### ISSUE THREAD

**Issue by Maryse47** [mjec/fido2-hmac-secret#9]
**Describe the bug**
bash-completions and fido2-hmac-secret-add-luks-key manpage are correctly created during build and available in `dist`  directory but `make install` doesn't work for them

**To Reproduce**
1. `make DESTDIR="/build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git" PREFIX=/usr SETCAP_BINARY=0 install`
2. Output of above:
```
install -g 0 -o 0 -p -m 0755 -D /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/bin/fido2-hmac-secret /build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git/usr/bin/fido2-hmac-secret
[ "0" -eq 0 ] || setcap cap_ipc_lock+ep /build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git/usr/bin/fido2-hmac-secret
install -g 0 -o 0 -p -m 0644 -D /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/share/man/man1/fido2-hmac-secret.1.gz /build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git/usr/share/man/man1/fido2-hmac-secret.1.gz
[ -f /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/share/bash-completion/completions/fido2-hmac-secret ] && install -g 0 -o 0 -p -m 0644 /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/share/bash-completion/completions/fido2-hmac-secret /build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git/usr/share/bash-completion/completions/fido2-hmac-secret || true
install: cannot create regular file '/build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git/usr/share/bash-completion/completions/fido2-hmac-secret': No such file or directory
[ -f /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/lib/initcpio/install/fido2-hmac-secret ] && install -g 0 -o 0 -p -m 0644 -D /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/lib/initcpio/install/fido2-hmac-secret /build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git/usr/lib/initcpio/install/fido2-hmac-secret || true
[ -f /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/lib/initcpio/hooks/fido2-hmac-secret ] && install -g 0 -o 0 -p -m 0644 -D /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/lib/initcpio/hooks/fido2-hmac-secret /build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git/usr/lib/initcpio/hooks/fido2-hmac-secret || true
[ -f /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/bin/fido2-hmac-secret-add-luks-key ] && install -g 0 -o 0 -p -m 0755 -D /build/fido2-hmac-secret-git/src/fido2-hmac-secret/dist/bin/fido2-hmac-secret-add-luks-key /build/fido2-hmac-secret-git/pkg/fido2-hmac-secret-git/usr/bin/fido2-hmac-secret-add-luks-key || true
```

**Expected behavior**
bash-completions and fido2-hmac-secret-add-luks-key manpage should be installed correctly.

**Environment:**
 - Operating system: Arch Linux
 - Version: https://github.com/mjec/fido2-hmac-secret/commit/e474de576325e0993112f95ad2c323966fab7849

**Comment by mjec** [comment]
For bash-completions: I suspect this is due to a missing `-D` on the `install` line.

For add-luks-key manpage: there is not `install` line for this.

I'll have a fix up later today.

**Comment by Maryse47** [comment]
@mjec manpage was fixed with this commit but bash-completion is still missing after `make install`. I also wonder if those `  || true` statements should be there as I think missing files should show hard failures and not be silently accepted.

**Comment by mjec** [comment]
> I also wonder if those `|| true` statements should be there as I think missing files should show hard failures and not be silently accepted.

So the `|| true`s were definitely masking errors, so I've removed them. But the checking for file existence is important I think, because each of those files is optional to build (only comes with the `bash-completion` or `initcpio` targets), and I think `make release && sudo make install` should not fail.

**Comment by Maryse47** [comment]
Yes, I agree. I meant that if file exist in `DISTDIR` then it should be copied to `DESTDIR` successfully or show failure which is what you did now.
